filebeat.autodiscover:
  providers:
    - type: docker
      host: "unix:///var/run/docker.sock"
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

logging.level: info
logging.selectors: ["autodiscover", "docker", "cfgfile"]
logging.to_files: false